// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtimeAPI.Data;

#nullable disable

namespace UtimeAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240720110740_SeedCategory")]
    partial class SeedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UtimeAPI.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 1,
                            CategoryName = "Sport",
                            CreatedTime = new DateTime(2024, 7, 20, 14, 7, 38, 9, DateTimeKind.Local).AddTicks(5952)
                        },
                        new
                        {
                            ID = 2,
                            Amount = 2,
                            CategoryName = "Family",
                            CreatedTime = new DateTime(2024, 7, 20, 14, 7, 38, 9, DateTimeKind.Local).AddTicks(5974)
                        },
                        new
                        {
                            ID = 3,
                            Amount = 3,
                            CategoryName = "University",
                            CreatedTime = new DateTime(2024, 7, 20, 14, 7, 38, 9, DateTimeKind.Local).AddTicks(5980)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
