// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtimeAPI.Data;

#nullable disable

namespace UtimeAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240725164228_SeedActivity")]
    partial class SeedActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UtimeAPI.Models.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("UtimeAPI.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 1,
                            CategoryName = "Sport",
                            CreatedTime = new DateTime(2024, 7, 25, 19, 42, 27, 49, DateTimeKind.Local).AddTicks(5406)
                        },
                        new
                        {
                            ID = 2,
                            Amount = 2,
                            CategoryName = "Family",
                            CreatedTime = new DateTime(2024, 7, 25, 19, 42, 27, 49, DateTimeKind.Local).AddTicks(5428)
                        },
                        new
                        {
                            ID = 3,
                            Amount = 3,
                            CategoryName = "University",
                            CreatedTime = new DateTime(2024, 7, 25, 19, 42, 27, 49, DateTimeKind.Local).AddTicks(5430)
                        });
                });

            modelBuilder.Entity("UtimeAPI.Models.Activity", b =>
                {
                    b.HasOne("UtimeAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
